AWSTemplateFormatVersion: "2010-09-09"

Description: "NAT Gateway"

Parameters:
  SubnetPublicStackName:
    Type: String

Resources:
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: "vpc"

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - "ElasticIP"
          - "AllocationId"
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: ${SubnetPublicStackName}-subnet::id

Outputs:
  NatGatewayId:
    Description: "Nat Gatewat Id"
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-nat::gateway::id
    Value: { Ref: NatGateway }
