- name: cloudformation - ecs - service - render template
  template:
    src=roles/common/ecs/service/templates/service.yml.j2
    dest=roles/common/ecs/service/templates-generated/{{item.stack_name}}-template.yml
  with_items: "{{ service_items }}"

- name: cloudformation - ecs - service
  cloudformation:
    stack_name: "{{ item.stack_name }}"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    template: roles/common/ecs/service/templates-generated/{{item.stack_name}}-template.yml
  with_items: "{{ service_items }}"
