- name: cloudformation - ecs - service
  cloudformation:
    stack_name: "{{ item.stack_name }}"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    template: roles/common/ecs/service/templates/service.yml
    template_parameters:
      ClusterStackName: "{{ item.cluster_stack_name }}"
      DesiredCount: "{{ item.desired_count }}"
      LoadBalancerName: "{{ item.load_balancer_name }}"
      RoleEcsServiceStackName: "{{ item.role_ecs_service_stack_name }}"
      TaskDefinitionStackName: "{{ item.task_definition_stack_name }}"
  with_items: "{{ service_items }}"
