# hosted_zone_public_name: replace_with_public_hosted_zone_name
# ssl_certificate_id: replace_with_ssl_certificate_arn
ami_image_id: ami-809f84e6
# key_name: replace_with_key_name

security_group_load_balancer_web:
  - stack_name: cf-security-group-load-balancer-web
    security_group_ingress:
      - cidr_ip: 0.0.0.0/0
        from_port: 80
        ip_protocol: tcp
        to_port: 80
      - cidr_ip: 0.0.0.0/0
        from_port: 443
        ip_protocol: "tcp"
        to_port: 443
    vpc_stack_name: "{{ vpc_stack_name }}"

load_balancer_web:
  - stack_name: cf-load-balancer-web
    cross_zone: true
    listeners:
      - instance_port: 80
        instance_protocol: "HTTP"
        load_balancer_port: 80
        protocol: "HTTP"
      - instance_port: 80
        instance_protocol: "HTTP"
        load_balancer_port: 443
        protocol: "HTTPS"
        ssl_certificate_id: "{{ ssl_certificate_id }}"
    name: "load-balancer-web"
    scheme: "internet-facing"
    security_group_stack_names:
      - "{{ security_group_load_balancer_web[0].stack_name }}"
    subnet_stack_names:
      - "{{ subnet_public_1_stack_name }}"
      - "{{ subnet_public_2_stack_name }}"
      - "{{ subnet_public_3_stack_name }}"

security_group_ec2_instance_web:
  - stack_name: cf-security-group-ec2-instance-web
    security_group_ingress:
      - from_port: 80
        ip_protocol: tcp
        security_group_stack_name: "{{ security_group_load_balancer_web[0].stack_name }}"
        to_port: 80
    vpc_stack_name: "{{ vpc_stack_name }}"

security_group_ec2_instance_mongo:
  - stack_name: cf-security-group-ec2-instance-mongo
    security_group_ingress:
      - from_port: 27017
        ip_protocol: tcp
        security_group_stack_name: "{{ security_group_ec2_instance_web[0].stack_name }}"
        to_port: 27017
      - from_port: 27017
        ip_protocol: tcp
        security_group_self_referencing: true
        to_port: 27017
    vpc_stack_name: "{{ vpc_stack_name }}"

role_launch_configuration:
  - stack_name: cf-role-launch-configuration
    service: "ec2.amazonaws.com"
    policies:
      - policy_name: "RoleLaunchConfigurationEcs"
        actions:
          - "ecs:DeregisterContainerInstance"
          - "ecs:DiscoverPollEndpoint"
          - "ecs:Poll"
          - "ecs:RegisterContainerInstance"
          - "ecs:StartTelemetrySession"
          - "ecs:Submit*"
        resource: "*"
      - policy_name: "RoleLaunchConfigurationLogs"
        actions:
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
        resource: "arn:aws:logs:*:*:*"
      - policy_name: "RoleLaunchConfigurationEcr"
        actions:
          - "ecr:GetAuthorizationToken"
          - "ecr:BatchCheckLayerAvailability"
          - "ecr:GetDownloadUrlForLayer"
          - "ecr:BatchGetImage"
        resource: "*"
      - policy_name: "RoleLaunchConfigurationRoute53"
        actions:
          - "route53:ChangeResourceRecordSets"
          - "route53:GetHostedZone"
          - "route53:ListResourceRecordSets"
        resource: "arn:aws:route53:::*"
      - policy_name: "RoleLaunchConfigurationS3"
        actions:
          - "s3:GetObject"
        resource: "arn:aws:s3:::*"

instance_profile_launch_configuration:
  - stack_name: cf-instance-profile-launch-configuration
    role_stack_names:
      - "{{ role_launch_configuration[0].stack_name }}"

role_ecs_service:
  - stack_name: cf-role-ecs-service
    service: "ecs.amazonaws.com"
    policies:
      - policy_name: "RoleEcsService"
        actions:
          - "ec2:AuthorizeSecurityGroupIngress"
          - "ec2:Describe*"
          - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"
          - "elasticloadbalancing:Describe*"
          - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
        resource: "*"

log_group:
  - stack_name: cf-log-group
    log_group_name: "symfony-api-swagger-jwt"
    retention_in_days: 3

cluster_launch_configuration_mongo:
  - stack_name: cf-cluster-mongo
    cluster_name: "cluster-mongo"

launch_configuration_auto_scaling_group_mongo:
  - stack_name: cf-launch-configuration-auto-scaling-group-mongo
    lc_associate_public_ip_address: false
    lc_cluster_stack_name: "{{ cluster_launch_configuration_mongo[0].stack_name }}"
    lc_iam_instance_profile_stack_name: "{{ instance_profile_launch_configuration[0].stack_name }}"
    lc_image_id: "{{ ami_image_id }}"
    lc_instance_type: "t2.micro"
    lc_key_name: "{{ key_name }}"
    lc_security_group_stack_names:
      - "{{ security_group_ec2_instance_mongo[0].stack_name }}"
    lc_user_data_aws_cli: true
    lc_user_data_hosted_zone_stack_name: "{{ hosted_zone_private_stack_name }}"
    asg_desired_capacity: 3
    asg_health_check_type: "EC2"
    asg_max_size: 3
    asg_min_size: 1
    asg_vpc_zone_identifiers:
      - "{{ subnet_private_1_stack_name }}"
      - "{{ subnet_private_2_stack_name }}"
      - "{{ subnet_private_3_stack_name }}"

task_definition_service_mongo:
  - stack_name: cf-task-definition-service-mongo
    container_definitions:
      - name: "mongo"
        cpu: 1024
        essential: true
        image: "bendbennett/mongo-seeded:v0.3.0"
        log_configuration:
          log_driver: "awslogs"
          options:
            awslogs_region: "{{ region }}"
            awslogs_group_name: "symfony-api-swagger-jwt"
            awslogs_stream_prefix: "mongo"
        memory: 993
        port_mappings:
          - container_port: 27017
            host_port: 27017
    deployment_configuration:
      minimum_healthy_percent: 50
    family: "mongo"
    cluster_stack_name: "{{ cluster_launch_configuration_mongo[0].stack_name }}"
    desired_count: 3

cluster_launch_configuration_web:
  - stack_name: cf-cluster-web
    cluster_name: "cluster-web"

launch_configuration_auto_scaling_group_web:
  - stack_name: cf-launch-configuration-auto-scaling-group-web
    lc_associate_public_ip_address: false
    lc_cluster_stack_name: "{{ cluster_launch_configuration_web[0].stack_name }}"
    lc_iam_instance_profile_stack_name: "{{ instance_profile_launch_configuration[0].stack_name }}"
    lc_image_id: "{{ ami_image_id }}"
    lc_instance_type: "t2.micro"
    lc_key_name: "{{ key_name }}"
    lc_security_group_stack_names:
      - "{{ security_group_ec2_instance_web[0].stack_name }}"
    asg_desired_capacity: 3
    asg_health_check_type: "EC2"
    asg_max_size: 3
    asg_min_size: 1
    asg_vpc_zone_identifiers:
      - "{{ subnet_private_1_stack_name }}"
      - "{{ subnet_private_2_stack_name }}"
      - "{{ subnet_private_3_stack_name }}"

task_definition_service_web:
  - stack_name: cf-task-definition-service-web
    container_definitions:
      - name: "nginx"
        cpu: 256
        essential: true
        image: "bendbennett/nginx:v0.1.0"
        links:
          - php
        log_configuration:
          log_driver: "awslogs"
          options:
            awslogs_region: "{{ region }}"
            awslogs_group_name: "symfony-api-swagger-jwt"
            awslogs_stream_prefix: "nginx"
        memory: 128
        port_mappings:
          - container_port: 80
            host_port: 80
        volumes_from:
          - source_container: src
            read_only: false
      - name: "php"
        cpu: 756
        environment:
          - name: SY_MONGODB_SERVER
            value: "mongodb://mongo-rs1.internal.synaptology.net:27017,mongo-rs2.internal.synaptology.net:27017,mongo-rs3.internal.synaptology.net:27017/?replicaSet=rs0"
        essential: true
        image: "bendbennett/php7-fpm:v0.3.0"
        log_configuration:
          log_driver: "awslogs"
          options:
            awslogs_region: "{{ region }}"
            awslogs_group_name: "symfony-api-swagger-jwt"
            awslogs_stream_prefix: "php-fpm"
        memory: 853
        volumes_from:
          - source_container: src
            read_only: false
      - name: "src"
        command: [ "ping", "127.0.0.1", "-q" ]
        cpu: 12
        essential: true
        image: "bendbennett/symfony-api-swagger-jwt-src:v0.1.0"
        memory: 12
    deployment_configuration:
      minimum_healthy_percent: 50
    family: "web"
    cluster_stack_name: "{{ cluster_launch_configuration_web[0].stack_name }}"
    desired_count: 3
    load_balancers:
      - container_name: "nginx"
        container_port: 80
        load_balancer_name: "{{ load_balancer_web[0].name }}"
    role_ecs_service_stack_name: "{{ role_ecs_service[0].stack_name }}"

record_set:
  - stack_name: cf-record-set
    hosted_zone_name: "{{ hosted_zone_public_name }}"
    name: "demo.{{ hosted_zone_public_name }}"
    resource_records:
      - "{{ load_balancer_web[0].stack_name }}"
    ttl: 60
    type: CNAME

record_set_private:
  - hosted_zone_name: "{{ hosted_zone_private_name }}"
    name: mongo-rs1
    type: A
  - hosted_zone_name: "{{ hosted_zone_private_name }}"
    name: mongo-rs2
    type: A
  - hosted_zone_name: "{{ hosted_zone_private_name }}"
    name: mongo-rs3
    type: A

site_down:
  - "{{ record_set[0].stack_name }}"
  - "{{ task_definition_service_web[0].stack_name }}"
  - "{{ launch_configuration_auto_scaling_group_web[0].stack_name }}"
  - "{{ cluster_launch_configuration_web[0].stack_name }}"
  - "{{ task_definition_service_mongo[0].stack_name }}"
  - "{{ launch_configuration_auto_scaling_group_mongo[0].stack_name }}"
  - "{{ cluster_launch_configuration_mongo[0].stack_name }}"
  - "{{ log_group[0].stack_name }}"
  - "{{ role_ecs_service[0].stack_name }}"
  - "{{ instance_profile_launch_configuration[0].stack_name }}"
  - "{{ role_launch_configuration[0].stack_name }}"
  - "{{ security_group_ec2_instance_mongo[0].stack_name }}"
  - "{{ security_group_ec2_instance_web[0].stack_name }}"
  - "{{ load_balancer_web[0].stack_name }}"
  - "{{ security_group_load_balancer_web[0].stack_name }}"
