- name: cloudformation - subnet - private
  cloudformation:
    stack_name: "{{ item.value.stack_name }}"
    state: "absent"
    region: "{{ region }}"
  with_dict: "{{ private_subnets }}"

- name: cloudformation - subnet - public
  cloudformation:
    stack_name: "{{ item.value.stack_name }}"
    state: "absent"
    region: "{{ region }}"
  with_dict: "{{ public_subnets }}"

- name: cloudformation - vpc
  cloudformation:
    stack_name: "{{ vpc.stack_name }}"
    state: "absent"
    region: "{{ region }}"
