- name: cloudformation - ecs - task-definition-service - render template
  template:
    src=roles/common/ecs/task-definition-service/templates/task-definition-service.yml.j2
    dest=roles/common/ecs/task-definition-service/templates-generated/{{item.stack_name}}-template.yml
  with_items: "{{ task_definition_service_items }}"
  check_mode: no

- name: cloudformation - ecs - task-definition-service
  cloudformation:
    stack_name: "{{ item.stack_name }}"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    template: roles/common/ecs/task-definition-service/templates-generated/{{item.stack_name}}-template.yml
  with_items: "{{ task_definition_service_items }}"
