- name: cloudformation - vpc
  cloudformation:
    stack_name: "{{ vpc_stack_name }}"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    template: "{{ vpc_template }}"

- name: cloudformation - subnet - public
  cloudformation:
    stack_name: "{{ item.value.stack_name }}"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    template: "{{ subnet_public_template }}"
    template_parameters:
      SubnetAvailabilityZone: "{{ item.value.availability_zone }}"
      SubnetCidrBlock: "{{ item.value.cidr_block }}"
      VPCStackName: "{{ vpc_stack_name }}"
  with_dict: "{{ public_subnets }}"

- name: cloudformation - subnet - private
  cloudformation:
    stack_name: "{{ item.value.stack_name }}"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    template: "{{ subnet_private_template }}"
    template_parameters:
      SubnetAvailabilityZone: "{{ item.value.availability_zone }}"
      SubnetCidrBlock: "{{ item.value.cidr_block }}"
      SubnetPublicStackName: "{{ item.value.subnet_public_stack_name }}"
      VPCStackName: "{{ vpc_stack_name }}"
  with_dict: "{{ private_subnets }}"
