- name: cloudformation - vpc
  cloudformation:
    stack_name: "{{ api.vpc.stack_name }}"
    state: "present"
    region: "{{ api.region }}"
    disable_rollback: true
    template: "{{ vpc.template }}"
    template_parameters:
      VPCCidrBlock: "{{ api.vpc.cidr_block }}"
#
#- name: cloudformation - subnet - public
#  cloudformation:
#    stack_name: "{{ item.value.stack_name }}"
#    state: "present"
#    region: "{{ region }}"
#    disable_rollback: true
#    template: "{{ subnet_public_template }}"
#    template_parameters:
#      SubnetAvailabilityZone: "{{ item.value.availability_zone }}"
#      SubnetCidrBlock: "{{ item.value.cidr_block }}"
#      SubnetName: "{{ item.value.stack_name }}"
#      VPCStackName: "{{ vpc.stack_name }}"
#  with_dict: "{{ public_subnets }}"
#
#- name: cloudformation - subnet - private
#  cloudformation:
#    stack_name: "{{ item.value.stack_name }}"
#    state: "present"
#    region: "{{ region }}"
#    disable_rollback: true
#    template: "{{ subnet_private_template }}"
#    template_parameters:
#      SubnetAvailabilityZone: "{{ item.value.availability_zone }}"
#      SubnetCidrBlock: "{{ item.value.cidr_block }}"
#      SubnetName: "{{ item.value.stack_name }}"
#      SubnetPublicStackName: "{{ item.value.subnet_public_stack_name }}"
#      VPCStackName: "{{ vpc.stack_name }}"
#  with_dict: "{{ private_subnets }}"
