security_group_load_balancer_web:
  - stack_name: cf-security-group-load-balancer-web
    cidr_ip: 0.0.0.0/0
    from_port: 80
    ip_protocol: tcp
    security_group_type: "cidr_ip"
    to_port: 80
    vpc_stack_name: "{{ vpc.stack_name }}"

load_balancer_web:
  - stack_name: cf-load-balancer-web
    cross_zone: true
    listeners:
      - instance_port: 80
        instance_protocol: "HTTP"
        load_balancer_port: 80
        protocol: "HTTP"
    name: "load-balancer-site"
    security_group_stack_names:
      - "{{ security_group_load_balancer_web[0].stack_name }}"
    subnet_stack_names:
      - "{{ subnet_public[0].stack_name }}"
      - "{{ subnet_public[1].stack_name }}"

security_group_ec2_instance_web:
  - stack_name: cf-security-group-ec2-instance-web
    from_port: 80
    ip_protocol: tcp
    security_group_stack_name: "{{ security_group_load_balancer_web[0].stack_name }}"
    security_group_type: "source_security_group_id"
    to_port: 80
    vpc_stack_name: "{{ vpc.stack_name }}"

role_launch_configuration:
  - stack_name: cf-role-launch-configuration
    service: "ec2.amazonaws.com"
    policies:
      - policy_name: "RoleLaunchConfigurationEcs"
        actions:
          - "ecs:DeregisterContainerInstance"
          - "ecs:DiscoverPollEndpoint"
          - "ecs:Poll"
          - "ecs:RegisterContainerInstance"
          - "ecs:StartTelemetrySession"
          - "ecs:Submit*"
        resource: "*"
      - policy_name: "RoleLaunchConfigurationLogs"
        actions:
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
        resource: "arn:aws:logs:*:*:*"
      - policy_name: "RoleLaunchConfigurationEcr"
        actions:
          - "ecr:GetAuthorizationToken"
          - "ecr:BatchCheckLayerAvailability"
          - "ecr:GetDownloadUrlForLayer"
          - "ecr:BatchGetImage"
        resource: "*"

instance_profile_launch_configuration:
  - stack_name: cf-instance-profile-launch-configuration
    role_stack_names:
      - "{{ role_launch_configuration[0].stack_name }}"

cluster_launch_configuration_web:
  - stack_name: cf-cluster-web
    cluster_name: "cluster-site"

launch_configuration_auto_scaling_group_web:
  - stack_name: cf-launch-configuration-auto-scaling-group-web
    lc_associate_public_ip_address: false
    lc_cluster_stack_name: "{{ cluster_launch_configuration_web[0].stack_name }}"
    lc_iam_instance_profile_stack_name: "{{ instance_profile_launch_configuration[0].stack_name }}"
    lc_image_id: "ami-bf9481db"
    lc_instance_type: "t2.micro"
    lc_key_name: "synaptology-administrator"
    lc_security_group_stack_names:
      - "{{ security_group_ec2_instance_web[0].stack_name }}"
    asg_desired_capacity: 2
    asg_health_check_type: "EC2"
    asg_max_size: 2
    asg_min_size: 1
    asg_vpc_zone_identifiers:
      - "{{ subnet_private[0].stack_name }}"
      - "{{ subnet_private[1].stack_name }}"

task_definition_web:
  - stack_name: cf-task-definition-web
    container_definitions:
      - name: "nginx"
        cpu: 256
        essential: true
        image: "bendbennett/nginx:v0.1.0"
        links:
          - php
        memory: 128
        port_mappings:
          - container_port: 80
            host_port: 80
        volumes_from:
          - source_container: src
            read_only: false
      - name: "php"
        cpu: 256
        essential: true
        image: "bendbennett/php7-fpm:v0.3.0"
        links:
          - mongo
        memory: 256
        volumes_from:
          - source_container: src
            read_only: false
      - name: "mongo"
        cpu: 256
        essential: true
        image: "bendbennett/mongo-seeded:v0.1.0"
        memory: 256
      - name: "src"
        command: [ "ping", "127.0.0.1", "-q" ]
        cpu: 128
        essential: true
        image: "bendbennett/symfony2-api-swagger-jwt-src:v0.1.0"
        memory: 12

role_ecs_service_web:
  - stack_name: cf-role-ecs-service-web
    service: "ecs.amazonaws.com"
    policies:
      - policy_name: "RoleEcsService"
        actions:
          - "ec2:AuthorizeSecurityGroupIngress"
          - "ec2:Describe*"
          - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"
          - "elasticloadbalancing:Describe*"
          - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
        resource: "*"

service_web:
  - stack_name: cf-service-web
    cluster_stack_name: "{{ cluster_launch_configuration_web[0].stack_name }}"
    desired_count: 2
    load_balancer_name: "{{ load_balancer_web[0].name }}"
    role_ecs_service_stack_name: "{{ role_ecs_service_web[0].stack_name }}"
    task_definition_stack_name: "{{ task_definition_web[0].stack_name }}"

site_down:
  - "{{ service_web[0].stack_name }}"
  - "{{ role_ecs_service_web[0].stack_name }}"
  - "{{ task_definition_web[0].stack_name }}"
  - "{{ launch_configuration_auto_scaling_group_web[0].stack_name }}"
  - "{{ cluster_launch_configuration_web[0].stack_name }}"
  - "{{ instance_profile_launch_configuration[0].stack_name }}"
  - "{{ role_launch_configuration[0].stack_name }}"
  - "{{ security_group_ec2_instance_web[0].stack_name }}"
  - "{{ load_balancer_web[0].stack_name }}"
  - "{{ security_group_load_balancer_web[0].stack_name }}"
