AWSTemplateFormatVersion: "2010-09-09"

Description: "Role"

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: "nginx"
          Essential: true
          Image: "nginx"
          Memory: 128
          Cpu: 1024
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
Outputs:
  TaskDefinitionId:
    Description: "Task Definition Id"
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-task::definition::id
    Value: { Ref: TaskDefinition }
