dependencies:
  - { role: common/ec2/vpc }
  - { role: common/ec2/network-acl }
  - { role: common/ec2/route-table-public }
  - { role: common/ec2/subnet-public }
  - { role: common/ec2/nat-gateway }
