
region: eu-west-2

vpc:
  stack_name: cf-vpc
  cidr_block: 10.0.0.0/16
  enable_dns_hostnames: true
  enable_dns_support: true
  instance_tenancy: default

network_acl:
  stack_name: cf-network-acl
  cidr_block_egress: 0.0.0.0/0
  cidr_block_ingress: 0.0.0.0/0
  protocol_egress: -1
  protocol_ingress: -1
  rule_action_egress: allow
  rule_action_ingress: allow
  rule_number_egress: 100
  rule_number_ingress: 100
  vpc_stack_name: "{{ vpc.stack_name }}"

route_table_public:
  - stack_name: cf-route-table-public-1
    destination_cidr_block: 0.0.0.0/0
    gateway_type: "internet"
    vpc_stack_name: "{{ vpc.stack_name }}"

subnet_public:
  - stack_name: cf-subnet-public-1
    availability_zone: eu-west-2a
    cidr_block: 10.0.0.0/24
    network_acl_stack_name: "{{ network_acl.stack_name }}"
    route_table_stack_name: "{{ route_table_public[0].stack_name }}"
    vpc_stack_name: "{{ vpc.stack_name }}"
  - stack_name: cf-subnet-public-2
    availability_zone: eu-west-2b
    cidr_block: 10.0.1.0/24
    network_acl_stack_name: "{{ network_acl.stack_name }}"
    route_table_stack_name: "{{ route_table_public[0].stack_name }}"
    vpc_stack_name: "{{ vpc.stack_name }}"

route_table_private:
  - stack_name: cf-route-table-private-1
    destination_cidr_block: 0.0.0.0/0
    gateway_type: "nat"
    subnet_public_stack_name: "{{ subnet_public[0].stack_name }}"
    vpc_stack_name: "{{ vpc.stack_name }}"
  - stack_name: cf-route-table-private-2
    destination_cidr_block: 0.0.0.0/0
    gateway_type: "nat"
    subnet_public_stack_name: "{{ subnet_public[1].stack_name }}"
    vpc_stack_name: "{{ vpc.stack_name }}"

subnet_private:
  - stack_name: cf-subnet-private-1
    availability_zone: eu-west-2a
    cidr_block: 10.0.128.0/24
    network_acl_stack_name: "{{ network_acl.stack_name }}"
    route_table_stack_name: "{{ route_table_private[0].stack_name }}"
    vpc_stack_name: "{{ vpc.stack_name }}"
  - stack_name: cf-subnet-private-2
    availability_zone: eu-west-2b
    cidr_block: 10.0.129.0/24
    network_acl_stack_name: "{{ network_acl.stack_name }}"
    route_table_stack_name: "{{ route_table_private[1].stack_name }}"
    vpc_stack_name: "{{ vpc.stack_name }}"

security_group_load_balancer:
  - stack_name: cf-security-group-load-balancer
    cidr_ip: 0.0.0.0/0
    from_port: 80
    ip_protocol: tcp
    security_group_type: "cidr_ip"
    to_port: 80
    vpc_stack_name: "{{ vpc.stack_name }}"

load_balancer:
  - stack_name: cf-load-balancer
    cross_zone: true
    listeners:
      - instance_port: 80
        instance_protocol: "HTTP"
        load_balancer_port: 80
        protocol: "HTTP"
    security_group_stack_names:
      - "{{ security_group_load_balancer[0].stack_name }}"
    subnet_stack_names:
      - "{{ subnet_public[0].stack_name }}"
      - "{{ subnet_public[1].stack_name }}"

security_group_ec2_instance:
  - stack_name: cf-security-group-ec2-instance
    from_port: 80
    ip_protocol: tcp
    security_group_stack_name: "{{ security_group_load_balancer[0].stack_name }}"
    security_group_type: "source_security_group_id"
    to_port: 80
    vpc_stack_name: "{{ vpc.stack_name }}"


