
region: eu-west-2

vpc:
  cidr_block: 10.0.0.0/16
  enable_dns_hostnames: true
  enable_dns_support: true
  instance_tenancy: default
  stack_name: cf-vpc

network_acl:
  stack_name: cf-network-acl
  vpc_stack_name: "{{ vpc.stack_name }}"
