AWSTemplateFormatVersion: "2010-09-09"

Description: "Route Table - private"

Parameters:
  DestinationCidrBlock:
    Type: String

  SubnetPublicStackName:
    Type: String

  VpcStackName:
    Type: String

Resources:
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: "vpc"

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - "ElasticIP"
          - "AllocationId"
      SubnetId:
        Fn::ImportValue:
          Fn::Sub: ${SubnetPublicStackName}-subnet::id

  Route:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: { Ref: DestinationCidrBlock }
      NatGatewayId: { Ref: NatGateway}
      RouteTableId: { Ref: RouteTable }

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue:
          Fn::Sub: ${VpcStackName}-vpc::id
      Tags:
        - Key: "Name"
          Value:
            Fn::Sub: ${AWS::StackName}

Outputs:
  RouteTablePrivateId:
    Description: "Route Table Private Id"
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-route::table::id
    Value: { Ref: RouteTable }
