AWSTemplateFormatVersion: "2010-09-09"

Description: "VPC"

Parameters:
  CidrBlock:
    Type: String

  EnableDnsHostnames:
    Type: String

  EnableDnsSupport:
    Type: String

  InstanceTenancy:
    Type: String


#  InternetGatewayName:
#    Type: String
#    Default: "cf-vpc-internet::gateway"

#  NetworkAclName:
#    Type: String
#    Default: "cf-vpc-network::acl"

#  RouteDestinationCidrBlock:
#    Type: String
#    Default: "0.0.0.0/0"

#  RouteTableName:
#    Type: String
#    Default: "cf-vpc-route::table"


#
#  VPCName:
#    Type: String
#    Default: "cf-vpc"

Resources:
  InternetGateway:
    Type: AWS::EC2::InternetGateway

#  NetworkAcl:
#    Type: AWS::EC2::NetworkAcl
#    Properties:
#      VpcId: { Ref: VPC }
#
#  NetworkAclEntryEgress:
#    Type: AWS::EC2::NetworkAclEntry
#    Properties:
#      CidrBlock: "0.0.0.0/0"
#      Egress: "true"
#      NetworkAclId: { Ref: NetworkAcl }
#      Protocol: "-1"
#      RuleAction: "allow"
#      RuleNumber: "100"
#
#  NetworkAclEntryIngress:
#    Type: AWS::EC2::NetworkAclEntry
#    Properties:
#      CidrBlock: "0.0.0.0/0"
#      Egress: "false"
#      NetworkAclId: { Ref: NetworkAcl }
#      Protocol: "-1"
#      RuleAction: "allow"
#      RuleNumber: "100"

#  Route:
#    Type: AWS::EC2::Route
#    DependsOn: VPCGatewayAttachment
#    Properties:
#      DestinationCidrBlock: { Ref: RouteDestinationCidrBlock }
#      GatewayId: { Ref: InternetGateway }
#      RouteTableId: { Ref: RouteTable }

#  RouteTable:
#    Type: AWS::EC2::RouteTable
#    Properties:
#      VpcId: { Ref: VPC }

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: { Ref: CidrBlock }
      EnableDnsHostnames: { Ref: EnableDnsHostnames }
      EnableDnsSupport: { Ref: EnableDnsSupport }
      InstanceTenancy: { Ref: InstanceTenancy }

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: { Ref: InternetGateway }
      VpcId: { Ref: VPC }

Outputs:
#  NetworkAclId:
#    Description: "Network Acl Id"
#    Value: { Ref: NetworkAcl }
#    Export:
#      Name:
#        Fn::Sub: ${AWS::StackName}-network::acl::id

#  RouteTableId:
#    Description: "Route Table Id"
#    Value: { Ref: RouteTable }
#    Export:
#      Name:
#        Fn::Sub: ${AWS::StackName}-route::table::id

  InternetGatewayId:
    Description: "Internet Gateway Id"
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-internet::gateway::id
    Value: { Ref: InternetGateway }

  VPCId:
    Description: "VPC Id"
    Value: { Ref: VPC }
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-vpc::id
